version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: ymtszw/elm_for_ci:0.19

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "elm.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run tests
          command: elm test
      - run:
          name: Build
          command: elm make src/Main.elm

      - save_cache:
          paths:
            - elm-stuff
          key: v1-dependencies-{{ checksum "elm.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  only-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
